// <auto-generated />
using System;
using Assignment1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assignment1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250401185146_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assignment1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Home"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Food"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("Assignment1.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("ProductIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("Quantities")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerEmail = "john@gmail.com",
                            CustomerName = "John Doe",
                            OrderDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductIds = new[] { 1, 4, 5 },
                            Quantities = new[] { 2, 1, 1 }
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerEmail = "jane@gmail.com",
                            CustomerName = "Jane Smith",
                            OrderDate = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductIds = new[] { 2, 10 },
                            Quantities = new[] { 1, 1 }
                        });
                });

            modelBuilder.Entity("Assignment1.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 5,
                            Description = "Harry Potter books for fantasy lovers",
                            LowStockThreshold = 10,
                            Name = "Harry Potter",
                            Price = 50f,
                            Quantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 5,
                            Description = "Hunger Games for dystopia lovers",
                            LowStockThreshold = 10,
                            Name = "Hunger Games",
                            Price = 40f,
                            Quantity = 50
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 5,
                            Description = "Classic fantasy novel",
                            LowStockThreshold = 10,
                            Name = "The Lord of the Rings",
                            Price = 60f,
                            Quantity = 30
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "New fast laptop for work and gaming",
                            LowStockThreshold = 10,
                            Name = "Laptop",
                            Price = 1500f,
                            Quantity = 30
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "Latest smartphone with great camera",
                            LowStockThreshold = 10,
                            Name = "Smartphone",
                            Price = 999f,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Description = "Noise-canceling wireless earbuds",
                            LowStockThreshold = 10,
                            Name = "Wireless Earbuds",
                            Price = 150f,
                            Quantity = 50
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Description = "Feature-packed smartwatch",
                            LowStockThreshold = 10,
                            Name = "Smartwatch",
                            Price = 250f,
                            Quantity = 3
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Description = "Powerful vacuum cleaner for home use",
                            LowStockThreshold = 10,
                            Name = "Vacuum Cleaner",
                            Price = 200f,
                            Quantity = 15
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            Description = "Automatic coffee maker",
                            LowStockThreshold = 10,
                            Name = "Coffee Maker",
                            Price = 80f,
                            Quantity = 40
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3,
                            Description = "Beautiful summer dress",
                            LowStockThreshold = 10,
                            Name = "Summer Dress",
                            Price = 25f,
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            Description = "Stylish leather jacket",
                            LowStockThreshold = 10,
                            Name = "Leather Jacket",
                            Price = 150f,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            Description = "Comfortable running shoes",
                            LowStockThreshold = 10,
                            Name = "Running Shoes",
                            Price = 120f,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3,
                            Description = "High-quality denim jeans",
                            LowStockThreshold = 10,
                            Name = "Jeans",
                            Price = 60f,
                            Quantity = 30
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 4,
                            Description = "Delicious milk chocolate",
                            LowStockThreshold = 10,
                            Name = "Chocolate Bar",
                            Price = 2.5f,
                            Quantity = 100
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 4,
                            Description = "Pure organic honey",
                            LowStockThreshold = 10,
                            Name = "Organic Honey",
                            Price = 15f,
                            Quantity = 9
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4,
                            Description = "Italian pasta",
                            LowStockThreshold = 10,
                            Name = "Pasta Pack",
                            Price = 5f,
                            Quantity = 75
                        });
                });

            modelBuilder.Entity("Assignment1.Models.Product", b =>
                {
                    b.HasOne("Assignment1.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Assignment1.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
