// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartInventoryManagementSystem.Data;

#nullable disable

namespace SmartInventoryManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250412220543_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Role", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Identity");
                });

            modelBuilder.Entity("SmartInventoryManagementSystem.Areas.ProductManagement.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", "Identity");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Home"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Food"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("SmartInventoryManagementSystem.Areas.ProductManagement.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("ProductIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("Quantities")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("OrderId");

                    b.ToTable("Orders", "Identity");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerEmail = "john@gmail.com",
                            CustomerName = "John Doe",
                            OrderDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductIds = new[] { 1, 4, 5 },
                            Quantities = new[] { 2, 1, 1 }
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerEmail = "jane@gmail.com",
                            CustomerName = "Jane Smith",
                            OrderDate = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductIds = new[] { 2, 10 },
                            Quantities = new[] { 1, 1 }
                        });
                });

            modelBuilder.Entity("SmartInventoryManagementSystem.Areas.ProductManagement.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", "Identity");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 5,
                            Description = "Harry Potter books for fantasy lovers",
                            LowStockThreshold = 10,
                            Name = "Harry Potter",
                            Price = 50f,
                            Quantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 5,
                            Description = "Hunger Games for dystopia lovers",
                            LowStockThreshold = 10,
                            Name = "Hunger Games",
                            Price = 40f,
                            Quantity = 50
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 5,
                            Description = "Classic fantasy novel",
                            LowStockThreshold = 10,
                            Name = "The Lord of the Rings",
                            Price = 60f,
                            Quantity = 30
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "New fast laptop for work and gaming",
                            LowStockThreshold = 10,
                            Name = "Laptop",
                            Price = 1500f,
                            Quantity = 30
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "Latest smartphone with great camera",
                            LowStockThreshold = 10,
                            Name = "Smartphone",
                            Price = 999f,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Description = "Noise-canceling wireless earbuds",
                            LowStockThreshold = 10,
                            Name = "Wireless Earbuds",
                            Price = 150f,
                            Quantity = 50
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Description = "Feature-packed smartwatch",
                            LowStockThreshold = 10,
                            Name = "Smartwatch",
                            Price = 250f,
                            Quantity = 3
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Description = "Powerful vacuum cleaner for home use",
                            LowStockThreshold = 10,
                            Name = "Vacuum Cleaner",
                            Price = 200f,
                            Quantity = 15
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            Description = "Automatic coffee maker",
                            LowStockThreshold = 10,
                            Name = "Coffee Maker",
                            Price = 80f,
                            Quantity = 40
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3,
                            Description = "Beautiful summer dress",
                            LowStockThreshold = 10,
                            Name = "Summer Dress",
                            Price = 25f,
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            Description = "Stylish leather jacket",
                            LowStockThreshold = 10,
                            Name = "Leather Jacket",
                            Price = 150f,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            Description = "Comfortable running shoes",
                            LowStockThreshold = 10,
                            Name = "Running Shoes",
                            Price = 120f,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3,
                            Description = "High-quality denim jeans",
                            LowStockThreshold = 10,
                            Name = "Jeans",
                            Price = 60f,
                            Quantity = 30
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 4,
                            Description = "Delicious milk chocolate",
                            LowStockThreshold = 10,
                            Name = "Chocolate Bar",
                            Price = 2.5f,
                            Quantity = 100
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 4,
                            Description = "Pure organic honey",
                            LowStockThreshold = 10,
                            Name = "Organic Honey",
                            Price = 15f,
                            Quantity = 9
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4,
                            Description = "Italian pasta",
                            LowStockThreshold = 10,
                            Name = "Pasta Pack",
                            Price = 5f,
                            Quantity = 75
                        });
                });

            modelBuilder.Entity("SmartInventoryManagementSystem.Areas.ProjectManagement.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("User", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartInventoryManagementSystem.Areas.ProjectManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartInventoryManagementSystem.Areas.ProjectManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInventoryManagementSystem.Areas.ProjectManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartInventoryManagementSystem.Areas.ProjectManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartInventoryManagementSystem.Areas.ProductManagement.Models.Product", b =>
                {
                    b.HasOne("SmartInventoryManagementSystem.Areas.ProductManagement.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartInventoryManagementSystem.Areas.ProductManagement.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
